import { EnhancedJiraTicket } from '../jira/types.js';
import { CodebaseAnalysis } from './types.js';
import { logger } from '../logger.js';
import { claudeClient } from '../claude/client.js';

export async function generateClaudeMd(
  ticket: EnhancedJiraTicket,
  analysis: CodebaseAnalysis
): Promise<string> {
  logger.info(`Generating CONTEXT.md for ticket ${ticket.key}`);

  const sections: string[] = [];

  // Header
  sections.push(`# ${ticket.key}: ${ticket.summary}`);
  sections.push('');
  sections.push(`**Status:** ${ticket.status}`);
  sections.push(`**Created:** ${new Date(ticket.created).toLocaleDateString()}`);
  if (ticket.epicKey) {
    sections.push(`**Epic:** ${ticket.epicKey}`);
  }
  if (ticket.components.length > 0) {
    sections.push(`**Components:** ${ticket.components.join(', ')}`);
  }
  sections.push('');
  sections.push('---');
  sections.push('');

  // Ticket Overview
  sections.push('## Ticket Overview');
  sections.push('');
  sections.push('### Description');
  sections.push('');
  sections.push(ticket.description || 'No description provided');
  sections.push('');

  if (ticket.acceptanceCriteria) {
    sections.push('### Acceptance Criteria');
    sections.push('');
    sections.push(ticket.acceptanceCriteria);
    sections.push('');
  }

  sections.push(`**Jira Link:** ${ticket.url}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // Technical Context
  sections.push('## Technical Context');
  sections.push('');

  sections.push('### Tech Stack');
  sections.push('');
  if (analysis.techStack.languages.length > 0) {
    sections.push(`**Languages:** ${analysis.techStack.languages.join(', ')}`);
  }
  if (analysis.techStack.frameworks.length > 0) {
    sections.push(`**Frameworks:** ${analysis.techStack.frameworks.join(', ')}`);
  }
  if (analysis.techStack.buildTools.length > 0) {
    sections.push(`**Build Tools:** ${analysis.techStack.buildTools.join(', ')}`);
  }
  if (analysis.techStack.testFrameworks.length > 0) {
    sections.push(`**Testing:** ${analysis.techStack.testFrameworks.join(', ')}`);
  }
  if (analysis.techStack.packageManager) {
    sections.push(`**Package Manager:** ${analysis.techStack.packageManager}`);
  }
  sections.push('');

  // Project Structure
  sections.push('### Project Structure');
  sections.push('');
  if (analysis.projectStructure.rootDirs.length > 0) {
    sections.push('**Key Directories:**');
    analysis.projectStructure.rootDirs.slice(0, 10).forEach((dir) => {
      sections.push(`- \`${dir}/\``);
    });
    sections.push('');
  }

  if (analysis.keyFiles.length > 0) {
    sections.push('**Important Files:**');
    analysis.keyFiles.forEach((file) => {
      sections.push(`- \`${file}\``);
    });
    sections.push('');
  }

  if (analysis.projectStructure.hasTests) {
    sections.push('✓ Tests are present in this repository');
    sections.push('');
  }

  sections.push('---');
  sections.push('');

  // Implementation Guidance (generated by Claude)
  sections.push('## Implementation Guidance');
  sections.push('');

  try {
    // Build codebase context for Claude
    const codebaseContext = buildCodebaseContext(analysis);

    // Get Claude's implementation suggestions
    const guidance = await claudeClient.generateImplementationGuidance(ticket, codebaseContext);
    sections.push(guidance);
  } catch (error: any) {
    logger.warn(`Failed to generate implementation guidance: ${error.message}`);
    sections.push('*Implementation guidance could not be generated automatically. Review the ticket requirements and codebase structure to determine the best approach.*');
  }

  sections.push('');
  sections.push('---');
  sections.push('');

  // Dependencies
  if (Object.keys(analysis.dependencies).length > 0) {
    sections.push('## Dependencies');
    sections.push('');

    if (analysis.dependencies.npm) {
      const deps = analysis.dependencies.npm.dependencies || {};
      const devDeps = analysis.dependencies.npm.devDependencies || {};

      if (Object.keys(deps).length > 0) {
        sections.push('### Production Dependencies');
        sections.push('');
        Object.entries(deps)
          .slice(0, 15)
          .forEach(([name, version]) => {
            sections.push(`- \`${name}\`: ${version}`);
          });
        sections.push('');
      }

      if (Object.keys(devDeps).length > 0) {
        sections.push('### Development Dependencies');
        sections.push('');
        Object.entries(devDeps)
          .slice(0, 10)
          .forEach(([name, version]) => {
            sections.push(`- \`${name}\`: ${version}`);
          });
        sections.push('');
      }
    }

    if (analysis.dependencies.pip) {
      sections.push('### Python Dependencies');
      sections.push('');
      analysis.dependencies.pip.slice(0, 15).forEach((dep: string) => {
        sections.push(`- \`${dep}\``);
      });
      sections.push('');
    }

    sections.push('---');
    sections.push('');
  }

  // Getting Started
  sections.push('## Getting Started');
  sections.push('');

  // Generate build/run commands based on tech stack
  const commands = generateBuildCommands(analysis);
  if (commands.length > 0) {
    sections.push('### Build & Run');
    sections.push('');
    sections.push('```bash');
    commands.forEach((cmd) => sections.push(cmd));
    sections.push('```');
    sections.push('');
  }

  // Testing commands
  if (analysis.projectStructure.hasTests) {
    const testCommands = generateTestCommands(analysis);
    if (testCommands.length > 0) {
      sections.push('### Running Tests');
      sections.push('');
      sections.push('```bash');
      testCommands.forEach((cmd) => sections.push(cmd));
      sections.push('```');
      sections.push('');
    }
  }

  sections.push('---');
  sections.push('');

  // Footer
  sections.push('## Notes');
  sections.push('');
  sections.push('- This CONTEXT.md was automatically generated by the Jira Ticket Monitor Agent');
  sections.push(`- Generated on: ${new Date().toISOString()}`);
  sections.push('- Review the ticket description and acceptance criteria carefully before starting work');
  sections.push('- Check related tickets for context and lessons learned');
  sections.push('');

  const content = sections.join('\n');
  logger.info(`Generated CONTEXT.md with ${content.length} characters`);

  return content;
}

function buildCodebaseContext(analysis: CodebaseAnalysis): string {
  const context: string[] = [];

  // Tech stack summary
  if (analysis.techStack.languages.length > 0) {
    context.push(`Languages: ${analysis.techStack.languages.join(', ')}`);
  }
  if (analysis.techStack.frameworks.length > 0) {
    context.push(`Frameworks: ${analysis.techStack.frameworks.join(', ')}`);
  }
  if (analysis.techStack.buildTools.length > 0) {
    context.push(`Build Tools: ${analysis.techStack.buildTools.join(', ')}`);
  }

  // Project structure
  if (analysis.projectStructure.rootDirs.length > 0) {
    context.push('\nKey Directories:');
    analysis.projectStructure.rootDirs.slice(0, 15).forEach((dir) => {
      context.push(`- ${dir}/`);
    });
  }

  // Important files
  if (analysis.keyFiles.length > 0) {
    context.push('\nImportant Files:');
    analysis.keyFiles.forEach((file) => {
      context.push(`- ${file}`);
    });
  }

  // Key dependencies (top 10)
  if (analysis.dependencies.npm) {
    const deps = Object.keys(analysis.dependencies.npm.dependencies || {}).slice(0, 10);
    if (deps.length > 0) {
      context.push('\nKey Dependencies:');
      deps.forEach((dep) => context.push(`- ${dep}`));
    }
  }

  return context.join('\n');
}

function generateBuildCommands(analysis: CodebaseAnalysis): string[] {
  const commands: string[] = [];

  if (analysis.techStack.packageManager === 'npm') {
    commands.push('# Install dependencies');
    commands.push('npm install');
    commands.push('');
    commands.push('# Build');
    commands.push('npm run build');
    commands.push('');
    commands.push('# Start development server');
    commands.push('npm run dev');
  } else if (analysis.techStack.buildTools.includes('Maven')) {
    commands.push('# Build with Maven');
    commands.push('mvn clean install');
    commands.push('');
    commands.push('# Run');
    commands.push('mvn spring-boot:run');
  } else if (analysis.techStack.buildTools.includes('Gradle')) {
    commands.push('# Build with Gradle');
    commands.push('./gradlew build');
    commands.push('');
    commands.push('# Run');
    commands.push('./gradlew bootRun');
  } else if (analysis.techStack.packageManager === 'pip') {
    commands.push('# Install dependencies');
    commands.push('pip install -r requirements.txt');
    commands.push('');
    commands.push('# Run');
    commands.push('python main.py');
  }

  return commands;
}

function generateTestCommands(analysis: CodebaseAnalysis): string[] {
  const commands: string[] = [];

  if (analysis.techStack.testFrameworks.includes('Jest')) {
    commands.push('npm test');
  } else if (analysis.techStack.testFrameworks.includes('Mocha')) {
    commands.push('npm test');
  } else if (analysis.techStack.testFrameworks.includes('pytest')) {
    commands.push('pytest');
  } else if (analysis.techStack.buildTools.includes('Maven')) {
    commands.push('mvn test');
  } else if (analysis.techStack.buildTools.includes('Gradle')) {
    commands.push('./gradlew test');
  } else {
    commands.push('# Check package.json or README for test commands');
  }

  return commands;
}
