import fs from 'fs/promises';
import path from 'path';
import { EnhancedJiraTicket } from '../jira/types.js';
import { RepositorySelection, BranchPreparationResult } from '../bitbucket/types.js';
import { prepareBranch, commitChanges, pushBranch } from '../bitbucket/operations.js';
import { addCommentToTicket } from '../jira/operations.js';
import { CodebaseAnalyzer } from '../codebase/analyzer.js';
import { generateClaudeMd } from '../codebase/claude-md-generator.js';
import { tempDirectoryManager } from '../temp/manager.js';
import { logger } from '../logger.js';

export class BranchPreparationWorkflow {
  private ticket: EnhancedJiraTicket;
  private repository: RepositorySelection;
  private tempDir: string | null = null;
  private repoPath: string | null = null;

  constructor(ticket: EnhancedJiraTicket, repository: RepositorySelection) {
    this.ticket = ticket;
    this.repository = repository;
  }

  async execute(): Promise<BranchPreparationResult> {
    try {
      logger.info(`Starting branch preparation workflow for ${this.ticket.key}`);

      // Step 1: Create temp directory
      this.tempDir = await tempDirectoryManager.createTempDir(this.ticket.key);
      this.repoPath = path.join(this.tempDir, 'repo');

      // Step 2: Clone repository and create branch
      logger.info(`Step 1/4: Cloning repository and creating branch`);
      const result = await prepareBranch(this.ticket, this.repository, this.repoPath);

      // Step 3: Analyze codebase
      logger.info(`Step 2/4: Analyzing codebase`);
      const analyzer = new CodebaseAnalyzer(this.repoPath);
      const analysis = await analyzer.analyzeRepository();

      // Step 4: Generate CONTEXT.md with implementation guidance
      logger.info(`Step 3/4: Generating CONTEXT.md with implementation guidance`);
      const contextMdContent = await generateClaudeMd(
        this.ticket,
        analysis
      );

      // Write CONTEXT.md to repository
      const contextMdPath = path.join(this.repoPath, 'CONTEXT.md');
      await fs.writeFile(contextMdPath, contextMdContent, 'utf-8');
      logger.info(`Written CONTEXT.md to ${contextMdPath}`);

      // Step 5: Commit and push
      logger.info(`Step 4/4: Committing and pushing changes`);
      const commitMessage = `${this.ticket.key}-add-CONTEXT.md

Automatically generated context document including:
- Ticket description and acceptance criteria
- Codebase analysis and tech stack
- Implementation guidance
- Related tickets and dependencies

Generated by Jira Ticket Agent`;

      const commitSha = await commitChanges(this.repoPath, commitMessage);
      result.commitSha = commitSha;

      await pushBranch(this.repoPath, result.branchName);

      // Step 6: Add Jira comment
      logger.info('Adding comment to Jira ticket');
      const jiraComment = `Branch created by Claude. CONTEXT.md generated with ticket details, codebase analysis, and implementation guidance.

Branch: \`${result.branchName}\`
View in Bitbucket: ${result.branchUrl}`;

      try {
        await addCommentToTicket(this.ticket.key, jiraComment);
      } catch (error) {
        logger.warn('Failed to add Jira comment (non-blocking):', error);
      }

      // Note: We don't assign the ticket since developers haven't taken it yet
      // The ticket remains in "To Do" status for developers to self-assign

      logger.info(`Branch preparation completed successfully for ${this.ticket.key}`);

      return result;
    } catch (error) {
      logger.error(`Branch preparation failed for ${this.ticket.key}:`, error);
      throw error;
    } finally {
      // Cleanup temp directory
      if (this.tempDir) {
        await this.cleanup();
      }
    }
  }

  private async cleanup(): Promise<void> {
    if (this.tempDir) {
      logger.info(`Cleaning up temp directory: ${this.tempDir}`);
      await tempDirectoryManager.cleanup(this.ticket.key);
    }
  }
}
